- name: creating 3 ec2 instances and r53
  hosts: localhost
  
  vars:
   zone: daws78s-rev.online
   instances:
    - db
    - backend
    - frontend

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
     instance_type: t2.micro
     name: "{{ item }}"
     security_group: Alltraffic-allow 
     image_id: ami-041e2ea9402c46c32
     tags:
      Name: "{{ item }}"

    loop:
    - "{{ instances }}"
    register: ec2_instance_info

  - name: print output:-
    ansible.builtin.debug:
     msg: "{{ ec2_instance_info }}"


  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: " {{ zone }}"
      record: " {{ item }}.{{ zone }}"
      type: A
      value: "{{ item.instances.private_ip_address }}"
      overwrite: true
      ttl: 1
    loop: "{{ ec2_instance_info.results }}"
