- name: installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove the index files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


- name: creating the directories
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download and copy the code
  ansible.builtin.unarchive:
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy backend cofig
  ansible.builtin.template:
    src: expense.config.j2
    dest: /etc/nginx/default.d/expense.conf

  notify: 
  - restart nginx

# - name: restart nginx
#   ansible.builtin.service:
#     name: nginx
#     state: restarted
